import type { Metadata, Viewport } from "next";
// Self-hosted variable fonts (no runtime dependency on Google). Exposed as "Inter Variable" / "JetBrains Mono Variable".
import "@fontsource-variable/inter";
import "@fontsource-variable/jetbrains-mono";
// CJK: split into ~100 unicode-range chunks, browsers fetch only the ones a page needs.
import "@fontsource-variable/noto-sans-sc";
import "./globals.css";
import { AppProviders } from "@/components/providers";
import { AppShell } from "@/components/layout/app-shell";
import { Toaster } from "@/components/ui/sonner";

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://arclaunch.top";
const TITLE = "ArcLaunch · Launch tokens on Arc, settled in USDC";
const DESC = "Zero-cost, fair-launch tokens on Arc. Every trade priced in USDC, LP locked forever, creators earn 75% of fees in USDC automatically.";

// Favicon / apple-touch-icon come from src/app/icon.png and src/app/apple-icon.png (generated by ops/brand.mjs).
export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: TITLE,
  description: DESC,
  applicationName: "ArcLaunch",
  openGraph: { title: TITLE, description: DESC, siteName: "ArcLaunch", type: "website", images: [{ url: "/brand/og.png", width: 1200, height: 630, alt: "ArcLaunch" }] },
  twitter: { card: "summary_large_image", title: TITLE, description: DESC, images: ["/brand/og.png"] },
};

export const viewport: Viewport = {
  themeColor: "#0b1020",
  width: "device-width",
  initialScale: 1,
  // explicitly allow pinch-zoom on mobile browsers (wallet in-app WebViews may still lock it themselves)
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
};

// Runs before paint so the persisted theme never flashes. `?theme=` / `?lang=` override and persist.
const themeScript = `(function(){try{var q=new URLSearchParams(location.search);var qt=q.get('theme');var ql=q.get('lang');if(qt==='terminal'||qt==='arc'){localStorage.setItem('arclaunch.theme',qt);}if(ql==='zh'||ql==='en'){localStorage.setItem('arclaunch.locale',ql);}var t=localStorage.getItem('arclaunch.theme');if(t==='terminal'||t==='arc'){document.documentElement.dataset.theme=t;}}catch(e){}})();`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Both brand themes are dark; the `dark` class keeps shadcn's dark variants active.
  return (
    <html lang="en" data-theme="arc" className="dark font-sans" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="min-h-full">
        <AppProviders>
          <AppShell>{children}</AppShell>
          <Toaster position="top-center" />
        </AppProviders>
      </body>
    </html>
  );
}
